### ISSUE TITLE
[BUG] Java  --javaIncludeComments --javaJackson leads to Compilationfailure

### ISSUE THREAD

**Issue by callyourai** [asyncapi/github-action-for-cli#382] opened 2024-03-22 15:10 UTC
### Describe the bug.

Java  --javaIncludeComments --javaJackson leads to Compilationfailure

### Expected behavior

Generating the models normally

### Screenshots

![image](https://github.com/asyncapi/github-action-for-cli/assets/160193928/4202903c-e032-405d-a57e-18ca2bcfe89c)

### How to Reproduce

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v2

      # Generating models from my AsyncAPI document
      - name: Generating models from my AsyncAPI document
        uses: asyncapi/github-action-for-cli@v3.1.1
        with:
          command: generate
          filepath: docs/asyncapi.yaml
          language: java
          parameters: --packageName=com.example --javaIncludeComments --javaJackson
          output: generated-models

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by jonaslagoni** [comment] 2024-03-22 15:37
We can move this to https://github.com/asyncapi/modelina

**Comment by jonaslagoni** [comment] 2024-03-22 15:37
@callyourai can you provide the AsyncAPI document as well?

**Comment by Shurtu-gal** [comment] 2024-03-22 15:40
> We can move this to https://github.com/asyncapi/modelina

Is it showing the same error if ran locally too ?

**Comment by jonaslagoni** [comment] 2024-03-22 15:45
Should have nothing to do with the github action yea 🙂

**Comment by Shurtu-gal** [comment] 2024-07-22 12:24
@jonaslagoni should this be closed or transferred ?

**Comment by jonaslagoni** [comment] 2024-08-13 05:52
Since no AsyncAPI document have been added, cant reproduce, just close it @Shurtu-gal.

@callyourai please reopen it in Modelina with input :v:

**Closed** 2024-08-13 05:53 UTC
Labels: bug
